version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_HOST: ${NEXT_PUBLIC_HOST}

  backend:
    build: ./backend
    ports:
      - 1337:1337
    environment:
      DATABASE_HOST: postgres
      DATABASE_CLIENT: postgres
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    command: "postgres -c port=${DATABASE_PORT}"

volumes:
  postgres:
